name: Deploy to Cloud Run
on:
 push:
 branches:
 - main # or whatever your branch name is
jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout code
 uses: actions/checkout@v4
 - name: Set up Google Cloud SDK
 uses: google-github-actions/setup-gcloud@v2
 with:
 project_id: saikiran9640
 install_components: 'beta'
 - name: Authenticate with Google Cloud
 uses: google-github-actions/auth@v2
 with:
 credentials_json: ${{ secrets.actions_github }}
 - name: Deploy to Cloud Run
 run: |
 gcloud run deploy hello-cloudrun \
 --source . \
 --region us-central1 \
 --platform managed \
 --allow-unauthenticated \
 --project saikiran9640
